name: ecommerce_pipeline
version: 1.0.0
config-version: 2

profile: ecommerce_pipeline

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  ecommerce_pipeline:
    staging:
      +schema: STAGING
      +materialized: table
    marts:
      +schema: MARTS
      +materialized: view