-- ── warehouse ───────────────────────────────────────────────
USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS ECOMMERCE_WH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    COMMENT = 'Warehouse for ecommerce pipeline';

-- ── database and schemas ────────────────────────────────────
CREATE DATABASE IF NOT EXISTS ECOMMERCE_DB;

USE DATABASE ECOMMERCE_DB;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS MARTS;

-- ── roles ───────────────────────────────────────────────────
USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS LOADER;
CREATE ROLE IF NOT EXISTS TRANSFORMER;

GRANT ROLE LOADER TO ROLE SYSADMIN;
GRANT ROLE TRANSFORMER TO ROLE SYSADMIN;

-- ── warehouse grants ────────────────────────────────────────
USE ROLE SYSADMIN;

GRANT USAGE ON WAREHOUSE ECOMMERCE_WH TO ROLE LOADER;
GRANT USAGE ON WAREHOUSE ECOMMERCE_WH TO ROLE TRANSFORMER;

-- ── loader grants (RAW only) ────────────────────────────────
GRANT USAGE ON DATABASE ECOMMERCE_DB TO ROLE LOADER;
GRANT USAGE ON SCHEMA ECOMMERCE_DB.RAW TO ROLE LOADER;
GRANT CREATE TABLE ON SCHEMA ECOMMERCE_DB.RAW TO ROLE LOADER;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ECOMMERCE_DB.RAW TO ROLE LOADER;

-- ── transformer grants ──────────────────────────────────────
GRANT USAGE ON DATABASE ECOMMERCE_DB TO ROLE TRANSFORMER;

GRANT USAGE ON SCHEMA ECOMMERCE_DB.RAW TO ROLE TRANSFORMER;
GRANT SELECT ON ALL TABLES IN SCHEMA ECOMMERCE_DB.RAW TO ROLE TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ECOMMERCE_DB.RAW TO ROLE TRANSFORMER;

GRANT USAGE ON SCHEMA ECOMMERCE_DB.STAGING TO ROLE TRANSFORMER;
GRANT CREATE TABLE ON SCHEMA ECOMMERCE_DB.STAGING TO ROLE TRANSFORMER;
GRANT CREATE VIEW ON SCHEMA ECOMMERCE_DB.STAGING TO ROLE TRANSFORMER;

GRANT USAGE ON SCHEMA ECOMMERCE_DB.MARTS TO ROLE TRANSFORMER;
GRANT CREATE TABLE ON SCHEMA ECOMMERCE_DB.MARTS TO ROLE TRANSFORMER;

-- ── assign roles to your user ───────────────────────────────
USE ROLE SECURITYADMIN;

GRANT ROLE LOADER TO USER DINHTHANHTRUNG;
GRANT ROLE TRANSFORMER TO USER DINHTHANHTRUNG;